# Python Recap — Write It Yourself
**A small dataset. One concept at a time. You write the code.**

This notebook is different from the others.
Every section shows you the concept, then gives you a blank to fill in.

**What we cover:**
1. Creating and loading data
2. First look commands
3. Variables and data types
4. Selecting columns and rows
5. Filtering
6. Basic statistics
7. Adding new columns
8. if / elif / else
9. Grouping
10. Simple charts

# 0. Setup — Run this first

In [3]:
# Run this cell first — it creates everything we need
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Our dataset — 10 students, 6 columns
# No file to upload — the data lives right here

data = {
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name":    ["Alice", "Bob", "Carol", "David", "Eva",
                "Frank", "Grace", "Henry", "Iris", "James"],
    "age":     [22, 19, 24, 21, 23, 20, 25, 18, 22, 21],
    "grade":   [85, 42, 91, 67, 78, 55, 93, 38, 72, 60],
    "city":    ["Berlin", "Munich", "Berlin", "Hamburg", "Berlin",
                "Munich", "Hamburg", "Berlin", "Munich", "Hamburg"],
    "passed":  ["Yes", "No", "Yes", "Yes", "Yes",
                "No", "Yes", "No", "Yes", "Yes"]
}

students = pd.DataFrame(data)
print("Dataset ready!")
print("Shape:", students.shape)

Dataset ready!
Shape: (10, 6)

# 1. First Look
These are the four commands you run on every dataset.
We will go through them one at a time.

## 1.1 — shape
Shows you how many rows and columns the dataset has.
```python
df.shape
```

In [4]:
# Run this — what does it show?
students.shape

(10, 6)

---
### Your turn
The result shows `(10, 5)`.
What does the **10** mean? What does the **5** mean?

Write your answer as a comment below and run the cell:

In [ ]:
# The 10 means: __________rows_________________________
# The 5 means:  ____________columns_______________________

## 1.2 — head()
Shows the first 5 rows of the dataset.
```python
df.head()
```

In [ ]:
# Run this
students.head()

    name  age  grade     city passed
0  Alice   22     85   Berlin    Yes
1    Bob   19     42   Munich     No
2  Carol   24     91   Berlin    Yes
3  David   21     67  Hamburg    Yes
4    Eva   23     78   Berlin    Yes

### Your turn — show the first **3** rows instead of 5

In [ ]:
students.head(3)

    name  age  grade    city passed
0  Alice   22     85  Berlin    Yes
1    Bob   19     42  Munich     No
2  Carol   24     91  Berlin    Yes

## 1.3 — dtypes
Shows the data type of each column.
```python
df.dtypes
```

In [ ]:
# Run this
students.dtypes

name      object
age        int64
grade      int64
city      object
passed    object
dtype: object

## 1.4 — info()
Full summary: column names, types, and how many values are NOT missing.
```python
df.info()
```

In [ ]:
# Run this
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     object
 1   age     10 non-null     int64
 2   grade   10 non-null     int64
 3   city    10 non-null     object
 4   passed  10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

### Your turn — use describe() to get statistics on numeric columns

In [ ]:
students.describe()

             age      grade
count  10.000000  10.000000
mean   21.500000  68.100000
std     2.173067  19.347409
min    18.000000  38.000000
25%    20.250000  56.250000
50%    21.500000  69.500000
75%    22.750000  83.250000
max    25.000000  93.000000

# 2. Selecting Columns
To work with one column, write the column name in square brackets.

```python
df["grade"]       # select one column
df[["name", "grade"]]  # select multiple columns
```

In [ ]:
# Example — select and print the grade column
students["grade"]

0    85
1    42
2    91
3    67
4    78
5    55
6    93
7    38
8    72
9    60
Name: grade, dtype: int64

### Your turn — select the age column

In [ ]:
students["age"]

0    22
1    19
2    24
3    21
4    23
5    20
6    25
7    18
8    22
9    21
Name: age, dtype: int64

### Your turn — select name AND city together

In [ ]:
# Select two columns at the same time
# Hint: use double brackets [[ ]]
students[["name", "city","age","grade"]]

    name     city  age  grade
0  Alice   Berlin   22     85
1    Bob   Munich   19     42
2  Carol   Berlin   24     91
3  David  Hamburg   21     67
4    Eva   Berlin   23     78
5  Frank   Munich   20     55
6  Grace  Hamburg   25     93
7  Henry   Berlin   18     38
8   Iris   Munich   22     72
9  James  Hamburg   21     60

# 3. Basic Statistics
These functions work on any numeric column.

| What you want | Function |
|---|---|
| Average | `.mean()` |
| Middle value | `.median()` |
| Highest value | `.max()` |
| Lowest value | `.min()` |
| Count | `.count()` |
| Standard deviation | `.std()` |
| Everything at once | `.describe()` |

In [ ]:
# Example — average grade
average_grade = students["grade"].mean()
print("Average grade:", average_grade)

Average grade: 68.1

### Your turn — calculate the average age

In [ ]:
# Calculate the average age
average_age = students["age"].mean()
print("Average age:", average_age)

Average age: 21.5

### Your turn — find the highest grade and the lowest grade

In [ ]:
# Highest grade
highest = students["grade"].max()
print("Highest grade:", highest)

# Lowest grade
lowest = students["grade"].min()
print("Lowest grade:", lowest)

Highest grade: 93
Lowest grade: 38

### Your turn — get all statistics of age at once

In [ ]:
# One function that gives everything
students["grade"].describe()

count    10.000000
mean     68.100000
std      19.347409
min      38.000000
25%      56.250000
50%      69.500000
75%      83.250000
max      93.000000
Name: grade, dtype: float64

# 4. Filtering — Selecting Specific Rows
Filtering keeps only the rows where a condition is True.

```python
# Pattern:
df[ df["column"] == "value" ]
```

Think of it like asking a question:
*"Give me all rows WHERE the city is Berlin"*

In [ ]:
students.head()

    name  age  grade     city passed
0  Alice   22     85   Berlin    Yes
1    Bob   19     42   Munich     No
2  Carol   24     91   Berlin    Yes
3  David   21     67  Hamburg    Yes
4    Eva   23     78   Berlin    Yes

In [ ]:
# Example — students from Berlin
berlin_students = students[ students["city"] == "Berlin" ]
print(berlin_students)

    name  age  grade    city passed
0  Alice   22     85  Berlin    Yes
2  Carol   24     91  Berlin    Yes
4    Eva   23     78  Berlin    Yes
7  Henry   18     38  Berlin     No

### Your turn — filter students from Munich

In [ ]:
# Students from Munich
munich_students = students[students["city"] == "Munich" ]
print(munich_students)

    name  age  grade    city passed
1    Bob   19     42  Munich     No
5  Frank   20     55  Munich     No
8   Iris   22     72  Munich    Yes

### Your turn — filter students who passed

In [ ]:
# Students who passed
passed_students = students[students["passed"] == "Yes" ]
print(passed_students)

    name  age  grade     city passed
0  Alice   22     85   Berlin    Yes
2  Carol   24     91   Berlin    Yes
3  David   21     67  Hamburg    Yes
4    Eva   23     78   Berlin    Yes
6  Grace   25     93  Hamburg    Yes
8   Iris   22     72   Munich    Yes
9  James   21     60  Hamburg    Yes

### Your turn — filter students with grade above 70
This time the condition uses `>` instead of `==`

In [ ]:
# Students with grade above 70
high_grades =  students[students["grade"] > 70 ]
print(high_grades)

    name  age  grade     city passed
0  Alice   22     85   Berlin    Yes
2  Carol   24     91   Berlin    Yes
4    Eva   23     78   Berlin    Yes
6  Grace   25     93  Hamburg    Yes
8   Iris   22     72   Munich    Yes

### Two conditions together
Use `&` for AND — both must be true
Use `|` for OR — at least one must be true

```python
# AND — both conditions
df[ (df["city"] == "Berlin") & (df["grade"] > 70) ]
```

In [ ]:
# Example — Berlin students with grade above 70
students[ (students["city"] == "Berlin") & (students["grade"] > 70) ]

    name  age  grade    city passed
0  Alice   22     85  Berlin    Yes
2  Carol   24     91  Berlin    Yes
4    Eva   23     78  Berlin    Yes

### Your turn — students from Munich OR Hamburg

In [ ]:
# Munich OR Hamburg
students[ (students["city"] == "Munich") | (students["city"] == "Hamburg") ]

    name  age  grade     city passed
1    Bob   19     42   Munich     No
3  David   21     67  Hamburg    Yes
5  Frank   20     55   Munich     No
6  Grace   25     93  Hamburg    Yes
8   Iris   22     72   Munich    Yes
9  James   21     60  Hamburg    Yes

# 5. Missing Values
Real datasets always have missing values.
Here is how to find and fix them.

In [ ]:
# First — let's add some missing values to our dataset to practice

df_messy = students.copy()
df_messy.loc[2, "age"]   = None    # Carol's age is now missing
df_messy.loc[5, "grade"] = None    # Frank's grade is now missing
df_messy.loc[8, "city"]  = None    # Iris's city is now missing

print("Dataset with missing values:")
print(df_messy)

Dataset with missing values:
    name   age  grade     city passed
0  Alice  22.0   85.0   Berlin    Yes
1    Bob  19.0   42.0   Munich     No
2  Carol   NaN   91.0   Berlin    Yes
3  David  21.0   67.0  Hamburg    Yes
4    Eva  23.0   78.0   Berlin    Yes
5  Frank  20.0    NaN   Munich     No
6  Grace  25.0   93.0  Hamburg    Yes
7  Henry  18.0   38.0   Berlin     No
8   Iris  22.0   72.0     None    Yes
9  James  21.0   60.0  Hamburg    Yes

In [ ]:
# Count missing values in each column
df_messy.isnull().sum()

name      0
age       1
grade     1
city      1
passed    0
dtype: int64

### Your turn — calculate missing values as a percentage

In [ ]:
len(berlin_students)

4

In [ ]:
# Percentage of missing values
# Hint: divide isnull().sum() by len(df_messy) and multiply by 100
(df_messy.isnull().sum() / len(df_messy) * 100)

name       0.0
age       10.0
grade     10.0
city      10.0
passed     0.0
dtype: float64

### Fixing missing values
Three strategies — choose based on the column:

```python
df["col"].fillna("Unknown")      # fill text with a word
df["col"].fillna(df["col"].mean())  # fill numbers with the average
df.dropna(subset=["col"])        # delete rows where col is missing
```

In [ ]:
# Example — fill missing city with "Unknown"
df_messy["city"] = df_messy["city"].fillna("Unknown")

In [ ]:
print(df_messy)

    name   age  grade     city passed
0  Alice  22.0   85.0   Berlin    Yes
1    Bob  19.0   42.0   Munich     No
2  Carol   NaN   91.0   Berlin    Yes
3  David  21.0   67.0  Hamburg    Yes
4    Eva  23.0   78.0   Berlin    Yes
5  Frank  20.0    NaN   Munich     No
6  Grace  25.0   93.0  Hamburg    Yes
7  Henry  18.0   38.0   Berlin     No
8   Iris  22.0   72.0  Unknown    Yes
9  James  21.0   60.0  Hamburg    Yes

### Your turn — fill missing grade with the average grade

In [ ]:
# Fill missing grade with the mean
mean_grade = df_messy["grade"].mean()
df_messy["grade"] = df_messy["grade"].fillna(mean_grade)

print("Missing grade after fix:", df_messy["grade"].isnull().sum())

Missing grade after fix: 0

In [ ]:
print(df_messy)

    name   age      grade     city passed
0  Alice  22.0  85.000000   Berlin    Yes
1    Bob  19.0  42.000000   Munich     No
2  Carol   NaN  91.000000   Berlin    Yes
3  David  21.0  67.000000  Hamburg    Yes
4    Eva  23.0  78.000000   Berlin    Yes
5  Frank  20.0  69.555556   Munich     No
6  Grace  25.0  93.000000  Hamburg    Yes
7  Henry  18.0  38.000000   Berlin     No
8   Iris  22.0  72.000000  Unknown    Yes
9  James  21.0  60.000000  Hamburg    Yes

# 6. Adding New Columns
You can create a new column and attach it to the dataframe.

```python
# Pattern:
df["new_column_name"] = something
```

In [ ]:
# Example — create a column that shows grade divided by 10
students["grade_out_of_10"] = students["grade"] / 10

print(students[["name", "grade", "grade_out_of_10"]])

print(students)

students.shape

    name  grade  grade_out_of_10
0  Alice     85              8.5
1    Bob     42              4.2
2  Carol     91              9.1
3  David     67              6.7
4    Eva     78              7.8
5  Frank     55              5.5
6  Grace     93              9.3
7  Henry     38              3.8
8   Iris     72              7.2
9  James     60              6.0
    name  age  grade     city passed  grade_out_of_10
0  Alice   22     85   Berlin    Yes              8.5
1    Bob   19     42   Munich     No              4.2
2  Carol   24     91   Berlin    Yes              9.1
3  David   21     67  Hamburg    Yes              6.7
4    Eva   23     78   Berlin    Yes              7.8
5  Frank   20     55   Munich     No              5.5
6  Grace   25     93  Hamburg    Yes              9.3
7  Henry   18     38   Berlin     No              3.8
8   Iris   22     72   Munich    Yes              7.2
9  James   21     60  Hamburg    Yes              6.0

(10, 6)

### Your turn — create a column called `age_next_year`

In [ ]:
# Each student's age next year
students["age_next_year"] = students["age"] + 1

In [ ]:
print(students)

    name  age  grade     city passed  grade_out_of_10  age_next_year
0  Alice   22     85   Berlin    Yes              8.5             23
1    Bob   19     42   Munich     No              4.2             20
2  Carol   24     91   Berlin    Yes              9.1             25
3  David   21     67  Hamburg    Yes              6.7             22
4    Eva   23     78   Berlin    Yes              7.8             24
5  Frank   20     55   Munich     No              5.5             21
6  Grace   25     93  Hamburg    Yes              9.3             26
7  Henry   18     38   Berlin     No              3.8             19
8   Iris   22     72   Munich    Yes              7.2             23
9  James   21     60  Hamburg    Yes              6.0             22

### Your turn — create a column called `passed_number`
`Yes` becomes `1`, `No` becomes `0`

In [ ]:
# Map text to numbers
students["passed_number"] = students["passed"].map({"Yes":1 , "No":0 })

print(students)

    name  age  grade     city passed  grade_out_of_10  age_next_year  \
0  Alice   22     85   Berlin    Yes              8.5             23
1    Bob   19     42   Munich     No              4.2             20
2  Carol   24     91   Berlin    Yes              9.1             25
3  David   21     67  Hamburg    Yes              6.7             22
4    Eva   23     78   Berlin    Yes              7.8             24
5  Frank   20     55   Munich     No              5.5             21
6  Grace   25     93  Hamburg    Yes              9.3             26
7  Henry   18     38   Berlin     No              3.8             19
8   Iris   22     72   Munich    Yes              7.2             23
9  James   21     60  Hamburg    Yes              6.0             22

   passed_number
0              1
1              0
2              1
3              1
4              1
5              0
6              1
7              0
8              1
9              1

# 7. if / elif / else
Python makes decisions using conditions.

```python
if condition:
    do this
elif other condition:
    do this instead
else:
    do this if nothing above was true
```

**Important: the indentation (4 spaces) is not optional — it is the rule.**

In [ ]:
# Example — classify one grade
grade = 85

if grade >= 90:
    print("A — Excellent")
elif grade >= 70:
    print("B — Good")
elif grade >= 50:
    print("C — Pass")
else:
    print("F — Fail")

### Your turn — change `grade = 85` to different values and see what happens

In [ ]:
# Try different values: 95, 75, 55, 35
grade =

if grade >= 90:
    print("A - Excellent")
elif grade >= 70:
    print("B - Good")
elif grade >= 50:
    print("C - Pass")
else:
    print("F - Fail")

### Apply if/elif to a whole column using a function + apply()
**Step 1** — write the function
**Step 2** — apply it to every row

In [ ]:
# Step 1 — define the function
def classify_grade(grade):
    if grade >= 90:
        return "A"
    elif grade >= 70:
        return "B"
    elif grade >= 50:
        return "C"
    else:
        return "F"

# Step 2 — apply to every row in the grade column
students["grade_letter"] = students["grade"].apply(classify_grade)

print(students[["name", "grade", "grade_letter"]])

### Your turn — create a column called `age_group`
Under 20 = `Young`, 20 to 22 = `Mid`, above 22 = `Senior`

In [ ]:
# Step 1 — write the function
def classify_age(age):
    if age < 20:
        return "Young"
    elif age <= ____:
        return "Mid"
    else:
        return "____"

# Step 2 — apply it
students["age_group"] = _____.apply(____)

print(students[["name", "age", "age_group"]])

# 8. For Loops
A for loop repeats the same action for each item in a list.

```python
for item in list:
    do something with item
```

In [ ]:
# Example — print each city name
cities = ["Berlin", "Munich", "Hamburg"]

for city in cities:
    print(city)

### Your turn — print each student's name

In [ ]:
# List of names
names = ["Alice", "Bob", "Carol", "David", "Eva"]

for ___ in names:
    print(___)

### Your turn — loop through classes and calculate something

In [ ]:
# Example — for each city, count how many students are from there
cities = ["Berlin", "Munich", "Hamburg"]

for city in cities:
    count = len(students[students["city"] == ______])
    print(city, ":", count, "students")

### Your turn — for each city, print the average grade

In [ ]:
cities = ["Berlin", "Munich", "Hamburg"]

for city in cities:
    subset  = students[students["city"] ==  ]
    avg     = subset["grade"]._____
    print(city, ":", round(avg, 1))

# 9. Grouping
`groupby()` groups rows together and calculates statistics per group.
It is faster and cleaner than writing a loop.

```python
df.groupby("column")["other_column"].mean()
```

In [ ]:
# Example — average grade per city
students.groupby("city")["grade"].mean().round(1)

### Your turn — average age per city

In [ ]:
students.groupby("city")["___"].___________

### Your turn — count how many students per city

In [ ]:
# Hint: use .size() instead of .mean()
students.groupby("city").______()

### Your turn — how many passed vs failed per city

In [ ]:
students.groupby(["city", "______"])["name"].count()

# 10. Simple Charts
Three chart types you will use most:

| Chart | When to use |
|---|---|
| Bar chart | Comparing categories |
| Histogram | Seeing how numbers are distributed |
| Line chart | Showing change over time |

## Bar chart

In [ ]:
# Example — count students per city
city_counts = students["city"].value_counts()
print(city_counts)

In [ ]:
city_counts.plot(kind="bar", color="steelblue")

plt.title("Students per City")
plt.xlabel("City")
plt.ylabel("Number of Students")
plt.xticks(rotation=0)

plt.show()

### Your turn — bar chart of passed vs failed

In [ ]:
passed_counts = ______________________

passed_counts.plot(kind="__", color="coral")

plt.title("Passed vs Failed")
plt.xlabel("")
plt.ylabel("Number of Students")
plt.xticks(rotation=0)

plt.show()

## Histogram

In [ ]:
# Example — distribution of grades
plt.hist(students["grade"], bins=5, color="steelblue", edgecolor="white")

plt.title("Grade Distribution")
plt.xlabel("Grade")
plt.ylabel("Number of Students")

plt.show()

### Your turn — histogram of age

## Add mean and median lines to a histogram

In [ ]:
plt.hist(students["grade"], bins=5, color="steelblue", edgecolor="white")

# Add a vertical line for the mean
plt.axvline(students["grade"].mean(),   color="red",   linestyle="--", label="Mean")

# Add a vertical line for the median
plt.axvline(students["grade"].median(), color="black", linestyle="-",  label="Median")

plt.title("Grade Distribution with Mean and Median")
plt.xlabel("Grade")
plt.ylabel("Number of Students")
plt.legend()

plt.show()

### Your turn — histogram of age with mean and median lines

# 11. Joining Tables
Two tables. One shared column. Combine them.

> *"In real projects data is never in one table. Customer info lives in one table, orders in another, products in another. Joining is how you bring them together."*

**Why use an ID to join?**
Because names can repeat. Two students can be called Alice. But `student_id = 101` is unique — it belongs to exactly one person. Real databases always join on IDs, never on names.

## The three tables we have

In [ ]:
# Table 1 — students (already exists from the setup cell)
print("Table 1 — students:")
print(students[["student_id", "name", "grade"]].head())
print()

# Table 2 — contact info
contacts = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105,
                   106, 107, 108, 109, 110],
    "email": ["alice@uni.de",  "bob@uni.de",   "carol@uni.de",
              "david@uni.de",  "eva@uni.de",   "frank@uni.de",
              "grace@uni.de",  "henry@uni.de", "iris@uni.de",
              "james@uni.de"]
})
print("Table 2 — contacts:")
print(contacts.head())
print()

# Table 3 — course registrations (only 5 students registered)
courses = pd.DataFrame({
    "student_id": [101, 103, 105, 107, 109],
    "course":     ["Data Science", "Machine Learning",
                   "Data Science", "Statistics", "Machine Learning"]
})
print("Table 3 — course registrations (only 5 students):")
print(courses)

## The basic merge — combining two tables
Pattern:
```python
table1.merge(table2, on="shared_column")
```
This is called an **inner join** by default.
It keeps only rows that exist in **both** tables.

In [ ]:
# Merge students with contacts using student_id
students_full = students.merge(contacts, on="student_id")

print("Result — students with email:")
print(students_full[["student_id", "name", "grade", "email"]])
print()
print("Rows:", len(students_full))
# All 10 students — because every student has a contact row

### Your turn — select only name and email from the merged table

In [ ]:
# Show only name and email columns from students_full
students_full[["___", "___"]]

## The four types of join
This is what makes joining powerful — you control which rows to keep.

| Join type | What it keeps | How to write it |
|---|---|---|
| Inner join | Only rows in **both** tables | `how="inner"` (default) |
| Left join | **All** rows from the left table | `how="left"` |
| Right join | **All** rows from the right table | `how="right"` |
| Outer join | **All** rows from **both** tables | `how="outer"` |

> *"Think of two circles overlapping. Inner = only the overlap. Left = the whole left circle. Outer = both circles completely."*

## Inner join — only matching rows

In [ ]:
# Inner join — students merged with courses
# Only students who registered for a course appear
inner = students.merge(courses, on="student_id", how="inner")

print("Inner join result:")
print(inner[["name", "grade", "course"]])
print()
print("Rows:", len(inner), "— only the 5 students who registered")

## Left join — keep all rows from the left table

In [ ]:
# Left join — all students appear
# Students who did not register get NaN in the course column
left = students.merge(courses, on="student_id", how="left")

print("Left join result:")
print(left[["name", "grade", "course"]])
print()
print("Rows:", len(left), "— all 10 students")
print()
print("NaN means: this student did not register for any course")

## Inner vs Left — the key difference
Run both and compare the output:
- **Inner:** 5 rows — only registered students
- **Left:** 10 rows — all students, NaN for those not registered

> *"Left join is safer for analysis. If you use inner join and someone has no course — they disappear from your data silently. Left join keeps them visible with NaN so you know they exist."*

In [ ]:
# Side by side comparison
print("INNER JOIN — rows:", len(inner))
print(inner[["name", "course"]])
print()
print("LEFT JOIN — rows:", len(left))
print(left[["name", "course"]])

### Your turn — count how many students have NaN in the course column after a left join

In [ ]:
# How many students did NOT register for a course?
# Hint: use .isnull().sum() on the course column
missing_course = left["course"].______().sum()
print("Students with no course registered:", missing_course)

### Your turn — filter the left join result to show only students who DID register

In [ ]:
# Show only rows where course is NOT missing
# Hint: use .notna() to find rows that are not NaN
registered_only = left[left["course"].______()]
print(registered_only[["name", "grade", "course"]])

## Outer join — keep everything from both tables

In [ ]:
# Add a student to courses that does NOT exist in students
courses_extra = pd.DataFrame({
    "student_id": [101, 103, 105, 107, 109, 999],  # 999 does not exist
    "course":     ["Data Science", "Machine Learning",
                   "Data Science", "Statistics",
                   "Machine Learning", "Python Basics"]
})

# Outer join — keeps all rows from BOTH tables
outer = students.merge(courses_extra, on="student_id", how="outer")

print("Outer join result:")
print(outer[["student_id", "name", "course"]])
print()
print("Notice student_id 999 — exists in courses but not in students")
print("Name is NaN because we have no student info for that ID")

## When to use which join

| Situation | Use |
|---|---|
| You only want complete records | Inner join |
| You want all students even if some data is missing | Left join |
| You want everything from both tables | Outer join |
| You want all records from the second table | Right join |

**Left join is the most common in data analysis.** It keeps your main table intact and adds extra information where available.

### Your turn — merge students with contacts AND courses in two steps

In [ ]:
# Step 1 — merge students with contacts
step1 = students.merge(contacts, on="___")

# Step 2 — merge the result with courses (use left join to keep all students)
step2 = step1.merge(courses, on="___", how="___")

# Show the result
print(step2[["name", "email", "course"]])
print()
print("Students without a course show NaN in the course column")

### Answer — only open after you have tried!

In [ ]:
# Answer
step1 = students.merge(contacts, on="student_id")
step2 = step1.merge(courses, on="student_id", how="left")
print(step2[["name", "email", "course"]])

# 11. Putting It All Together
One final exercise using everything from today.
No hints this time — try to write it from memory.

In [ ]:
# Final exercise — complete ALL of these steps:

# STEP 1: How many students have a grade above 60?
above_60 =
print("Students with grade above 60:", len(above_60))

In [ ]:
# STEP 2: What is the average grade for students who passed?
passed    = students[students["passed"] == ____]
avg_grade =

print("Average grade of passing students:", avg_grade)

In [ ]:
# STEP 3: Create a column called "result" with values "Pass" or "Fail"
#         using a function and apply()

def get_result(grade):
    if grade >= 50:
        return ______
    else:
        return _______

students["result"] = students["grade"].apply(get_result)
print(df)

In [ ]:
# STEP 4: Count how many Pass and how many Fail using groupby

In [ ]:
# STEP 5: Make a bar chart of average grade per city

### Answers — only open after you have tried!

In [ ]:
# STEP 1
above_60 = df[df["grade"] > 60]
print("Students with grade above 60:", len(above_60))

# STEP 2
passed    = df[df["passed"] == "Yes"]
avg_grade = passed["grade"].mean()
print("Average grade of passing students:", round(avg_grade, 1))

# STEP 3
def get_result(grade):
    if grade >= 50:
        return "Pass"
    else:
        return "Fail"

df["result"] = df["grade"].apply(get_result)
print(df[["name", "grade", "result"]])

# STEP 4
print(df.groupby("result")["name"].count())

# STEP 5
avg_by_city = df.groupby("city")["grade"].mean()
avg_by_city.plot(kind="bar", color="steelblue")
plt.title("Average Grade per City")
plt.xlabel("City")
plt.ylabel("Average Grade")
plt.xticks(rotation=0)
plt.show()

# Quick Reference Card
Keep this open while you work.

## Loading and looking
```python
df = pd.read_csv("file.csv")   # load a CSV file
df.shape                        # rows and columns
df.head()                       # first 5 rows
df.dtypes                       # column types
df.info()                       # full summary
df.describe()                   # statistics on numeric columns
```

## Selecting
```python
df["column"]                    # one column
df[["col1", "col2"]]            # multiple columns
df.loc[0]                       # one row by position
```

## Filtering
```python
df[df["col"] == "value"]        # equal to
df[df["col"] > 50]              # greater than
df[df["col"] != "value"]        # not equal to
df[(cond1) & (cond2)]           # AND
df[(cond1) | (cond2)]           # OR
```

## Statistics
```python
df["col"].mean()     # average
df["col"].median()   # middle value
df["col"].max()      # highest
df["col"].min()      # lowest
df["col"].std()      # spread
df["col"].count()    # how many values
df["col"].value_counts()  # count each unique value
```

## Missing values
```python
df.isnull().sum()                        # count missing
df["col"].fillna("Unknown")              # fill with word
df["col"].fillna(df["col"].mean())       # fill with average
df.dropna(subset=["col"])                # delete rows
```

## Adding columns
```python
df["new"] = df["col"] + 1               # calculation
df["new"] = df["col"].apply(function)   # custom function
df["new"] = df["col"].map({"A": 1})     # replace values
```

## Grouping
```python
df.groupby("col")["other"].mean()   # average per group
df.groupby("col").size()            # count per group
```

## Charts
```python
df["col"].value_counts().plot(kind="bar")   # bar chart
plt.hist(df["col"], bins=10)                # histogram
plt.axvline(df["col"].mean(), color="red")  # vertical line
plt.title("Title")
plt.xlabel("X label")
plt.ylabel("Y label")
plt.show()
```

## Joins
```python
# Basic merge (inner join by default)
result = table1.merge(table2, on="shared_column")

# Inner join — only rows that exist in BOTH tables
result = table1.merge(table2, on="shared_column", how="inner")

# Left join — ALL rows from table1, NaN where no match in table2
result = table1.merge(table2, on="shared_column", how="left")

# Right join — ALL rows from table2, NaN where no match in table1
result = table1.merge(table2, on="shared_column", how="right")

# Outer join — ALL rows from BOTH tables, NaN where no match
result = table1.merge(table2, on="shared_column", how="outer")

# Merge on multiple columns
result = table1.merge(table2, on=["col1", "col2"])

# Merge when columns have different names in each table
result = table1.merge(table2, left_on="id", right_on="student_id")

# Check result after merging
print(result.shape)               # how many rows and columns
print(result.isnull().sum())      # how many NaN values per column

# Find rows with no match (after left join)
no_match = result[result["col_from_table2"].isnull()]

# ─── WHEN TO USE WHICH ───────────────────────────────────────────
# Inner  → you only want complete records, no missing data
# Left   → keep all rows from your main table (most common)
# Right  → keep all rows from the second table (rare)
# Outer  → keep everything, see all gaps

# ─── REAL WORLD EXAMPLE ──────────────────────────────────────────
# students.merge(contacts, on="student_id")           # add emails
# students.merge(courses,  on="student_id", how="left") # add courses, keep all students
# step1.merge(step2, on="student_id", how="left")     # chain two merges
´´´